name: Create PR to Upstream

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout fork repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.name "Suzor-Antonin-EPITA"
          git config --global user.email "antonin.suzor@epita.fr"
          git config --global push.autoSetupRemote true

      - name: Sync fork with upstream
        run: |
          git remote add upstream https://github.com/theo-henon/demperm-social.git
          git fetch upstream main
          git checkout origin/main
          git merge upstream/main --allow-unrelated-histories -m "Sync fork with upstream"
          git push origin main || true

      - name: Run tests
        run: echo "This is a placeholder"

      - name: Push changes to a new branch on upstream
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          BRANCH_NAME="release-${TAG_NAME}"
          # Create a new branch locally
          git switch -c $BRANCH_NAME
          # Force push to upstream fork branch
          echo {{ secrets.ID_ED25519_EPITA }} > id_ed25519_epita
          ssh-agent bash -c "ssh-add /c/Users/anton/.ssh/id_ed25519_epita &> /dev/null; git push origin ; git push upstream --force"

      - name: Create PR on upstream
        env:
          GH_TOKEN: ${{ secrets.UPSTREAM_TOKEN }}
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          BRANCH_NAME="release-${TAG_NAME}"
          gh pr create \
            --repo theo-henon/demperm-social \
            --head $BRANCH_NAME \
            --base tttt \
            --title "Release $TAG_NAME" \
            --body "This PR syncs the latest forked \`main\` branch for release $TAG_NAME."
